services:
  lkplaces-spring:
    build: .
    container_name: lkplaces-spring
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/lkplaces
    ports:
      - 8081:8080
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=lkplaces_adm
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=lkplaces
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
#    restart: always
volumes:
  pgdata: