runtime: java
env: flex

runtime_config:
  jdk: openjdk8

handlers:
  - url: /.*
    script: this field is required, but ignored

#network:
#  instance_tag: lkplaces1
#  forwarded_ports:
#    - 8081

readiness_check:
  app_start_timeout_sec: 1200

manual_scaling:
  instances: 1
